import type { LabMode } from './types'

const n = (v: number) => Math.round(v).toLocaleString()

export const LAB_MODES: LabMode[] = [
  {
    id: 'sweep',
    label: 'Sweepstakes',
    spineStage: 'Capture',
    caption:
      'Raise prize quality — more golfers raise their hand nationwide. They join interested + favorite your product. Deeper tickets = stronger intent.',
    dialLabel: 'Prize quality',
    scopeLabel: 'Tickets / points entered (intent)',
    scopeMinLabel: '1 ticket',
    scopeMaxLabel: 'Heavy entry',
    pinLabel: 'Your prize',
    pinKey: 'national',
    stageKind: 'map-national',
    status: 'Eng confirm',
    showFavorite: true,
    showHands: true,
    act: 2,
    results: [
      { id: 'entries', label: 'Hands raised', format: (i) => n(400 + i * 85) },
      { id: 'favorites', label: 'Favorited product', format: (i) => n(280 + i * 62) },
      { id: 'intent', label: 'Avg intent', format: (_, s) => `${Math.round(20 + s * 0.75)}` },
      { id: 'cohort', label: 'Interested cohort', format: (i) => n(350 + i * 70) },
    ],
  },
  {
    id: 'pyl',
    label: 'Press Your Luck',
    spineStage: 'Activate',
    caption:
      'Fund free spins. Golfers watch/earn, favorite your product, spin. A win hits the feed — nearby golfers get pulled in and land on your listing.',
    dialLabel: 'Spin pool funding',
    scopeLabel: 'Earn path (video → quiz)',
    scopeMinLabel: 'Video only',
    scopeMaxLabel: 'Video + quiz',
    pinLabel: 'Your wheel',
    pinKey: 'national',
    stageKind: 'map-pyl',
    status: 'Live',
    showFavorite: true,
    act: 3,
    results: [
      { id: 'spins', label: 'Spins earned', format: (i) => n(120 + i * 40) },
      { id: 'favorites', label: 'Favorited', format: (i) => n(90 + i * 35) },
      { id: 'network', label: 'Pulled in by feed', format: (i) => n(30 + i * 18) },
      { id: 'pdp', label: 'Product page views', format: (i) => n(200 + i * 55) },
    ],
  },
  {
    id: 'learn',
    label: 'Learn & Earn',
    spineStage: 'Capture',
    caption: 'Raise the bounty — more golfers finish your video + quiz. Too low and they drop off mid-mission.',
    dialLabel: 'Bounty (points)',
    pinLabel: 'Mission',
    pinKey: 'national',
    stageKind: 'map-national',
    status: 'Live',
    showHands: true,
    act: 3,
    results: [
      { id: 'starts', label: 'Started video', format: (i) => n(500 + i * 40) },
      { id: 'done', label: 'Finished mission', format: (i) => n(80 + i * 55) },
      { id: 'finish', label: 'Finish rate', format: (i) => `${Math.round(12 + i * 0.7)}%` },
      { id: 'cost', label: 'Est. cost / complete', format: (i) => `$${(2.4 - i * 0.012).toFixed(2)}` },
    ],
  },
  {
    id: 'geo',
    label: 'Geo / event',
    spineStage: 'Activate',
    caption:
      'Drop a brand activation in Florida (or any market). Raise the incentive + radius — more golfers light up and move to the event. Pay only for verified show-ups.',
    dialLabel: 'Incentive (points / show-up)',
    scopeLabel: 'Radius (miles)',
    scopeMinLabel: 'Local',
    scopeMaxLabel: 'Wide market',
    pinLabel: 'Your event · FL',
    pinKey: 'fl',
    stageKind: 'map-event',
    status: 'Live',
    showPayPerResult: true,
    showHands: true,
    act: 5,
    results: [
      { id: 'scope', label: 'Golfers in radius', format: (i, s) => n(200 + i * 30 + s * 40) },
      { id: 'shows', label: 'Verified show-ups', format: (i, s) => n(20 + i * 12 + s * 4) },
      { id: 'cpa', label: 'Est. cost / show-up', format: (i) => `$${(18 - i * 0.08).toFixed(0)}` },
      { id: 'upfront', label: 'Upfront', format: () => '$0' },
    ],
  },
  {
    id: 'weather',
    label: 'Weather trigger',
    spineStage: 'Activate',
    caption:
      'Only golfers who got rained on (or high wind / wet regions) light up. Raise reach to include 7-day backfill and always-wet geos — still condition-true, not spray.',
    dialLabel: 'Who qualifies',
    scopeLabel: 'Condition window',
    scopeMinLabel: 'Rained today',
    scopeMaxLabel: '7-day + always-wet',
    pinLabel: 'Felt need',
    pinKey: 'rain',
    stageKind: 'map-weather',
    status: 'Live',
    act: 5,
    results: [
      { id: 'matched', label: 'Matched golfers', format: (i, s) => n(150 + i * 45 + s * 60) },
      { id: 'served', label: 'Saw your gear', format: (i, s) => n(120 + i * 40 + s * 50) },
      { id: 'relevance', label: 'On-condition', format: (i) => `${Math.round(70 + i * 0.25)}%` },
      { id: 'waste', label: 'Off-condition waste', format: (i) => `${Math.round(25 - i * 0.18)}%` },
    ],
  },
  {
    id: 'course',
    label: 'Course off-peak',
    spineStage: 'Activate',
    caption:
      'Dead Tuesday afternoon slots. Raise the points carrot — more golfers put their hand up and fill tee times. Lower still fills some.',
    dialLabel: 'Points for off-peak round',
    scopeLabel: 'Tee window',
    scopeMinLabel: '2–4pm only',
    scopeMaxLabel: 'All off-peak',
    pinLabel: 'Partner course',
    pinKey: 'course',
    stageKind: 'map-course',
    status: 'Live',
    showPayPerResult: true,
    showHands: true,
    act: 5,
    results: [
      { id: 'slots', label: 'Slots filled', format: (i, s) => n(8 + i * 0.35 + s * 0.15) },
      { id: 'fill', label: 'Fill rate', format: (i) => `${Math.round(15 + i * 0.65)}%` },
      { id: 'per', label: 'Est. $ / round', format: (i) => `$${(12 - i * 0.04).toFixed(0)}` },
      { id: 'hands', label: 'Hands up', format: (i) => n(40 + i * 8) },
    ],
  },
  {
    id: 'cohort',
    label: 'Cohort',
    spineStage: 'Cohort',
    caption:
      'Same map of people — now clustered by signal: favorited, high intent, bag match. Tighten focus to who you’ll activate next.',
    dialLabel: 'Signal depth required',
    scopeLabel: 'Segment focus',
    scopeMinLabel: 'Everyone who raised a hand',
    scopeMaxLabel: 'High-intent only',
    pinLabel: 'Working list',
    pinKey: 'national',
    stageKind: 'map-national',
    status: 'Live',
    showFavorite: true,
    act: 4,
    results: [
      { id: 'size', label: 'In working list', format: (i, s) => n(800 - s * 4 + i * 2) },
      { id: 'fav', label: 'With favorite', format: (i) => n(200 + i * 40) },
      { id: 'conf', label: 'List confidence', format: (i) => `${Math.round(40 + i * 0.5)}%` },
      { id: 'ready', label: 'Ready to activate', format: (i, s) => n(100 + i * 25 + s * 2) },
    ],
  },
  {
    id: 'offer',
    label: 'Follow-up offer',
    spineStage: 'Offer',
    caption:
      'Only the people who already raised a hand. Stronger offer → more claims. Unlisted product path only they can see.',
    dialLabel: 'Offer strength',
    scopeLabel: 'Who gets it',
    scopeMinLabel: 'All entrants',
    scopeMaxLabel: 'High intent only',
    pinLabel: 'Exclusive offer',
    pinKey: 'brand',
    stageKind: 'map-convert',
    status: 'Live',
    act: 6,
    results: [
      { id: 'eligible', label: 'Eligible golfers', format: (i, s) => n(600 - s * 3) },
      { id: 'claims', label: 'Claims', format: (i, s) => n(40 + i * 18 + (100 - s) * 0.2) },
      { id: 'rate', label: 'Claim rate', format: (i) => `${Math.round(8 + i * 0.45)}%` },
      { id: 'unlisted', label: 'Unlisted path', format: () => 'On' },
    ],
  },
  {
    id: 'contained',
    label: 'Contained %',
    spineStage: 'Convert',
    caption:
      'Golfers who activated for you have points in pocket. Raise the unlock % — more of them redeem on your product (contained, not a public coupon).',
    dialLabel: '% off when points hit your SKU',
    scopeLabel: 'Points vs cash on cart',
    scopeMinLabel: '30% points',
    scopeMaxLabel: '100% points',
    pinLabel: 'Your product',
    pinKey: 'brand',
    stageKind: 'map-convert',
    status: 'Live',
    act: 7,
    results: [
      { id: 'wallet', label: 'With your points', format: (i) => n(300 + i * 20) },
      { id: 'redeems', label: 'Redeemed on you', format: (i, s) => n(25 + i * 14 + s * 0.3) },
      { id: 'unlock', label: 'Unlock level', format: (i) => `${Math.round(5 + i * 0.2)}%` },
      { id: 'loop', label: 'Loop', format: () => 'Closed' },
    ],
  },
]

export const SPINE_STAGES = [
  'Aware',
  'Capture',
  'Cohort',
  'Activate',
  'Offer',
  'Convert',
  'Sustain',
] as const

export function getMode(id: string): LabMode {
  return LAB_MODES.find((m) => m.id === id) ?? LAB_MODES[0]
}
