import type { LabMode } from './types'

const n = (v: number) => Math.round(v).toLocaleString()

/** Abstract Lab configs — new partner ideas = new objects here, not new graphics. */
export const LAB_MODES: LabMode[] = [
  {
    id: 'sweep',
    label: 'Sweepstakes',
    spineStage: 'Capture',
    caption: 'Better giveaway → more hands. Enter → interested + favorited. More tickets = stronger intent.',
    dialLabel: 'Prize quality',
    scopeLabel: 'Tickets / points entered',
    scopeMinLabel: 'Light',
    scopeMaxLabel: 'Heavy',
    pinLabel: 'Prize',
    dotSemantic: 'Entrants',
    status: 'Eng confirm',
    showFavoritePulse: true,
    act: 2,
    results: [
      { id: 'entries', label: 'Entries', format: (i) => n(400 + i * 85) },
      { id: 'favorites', label: 'Favorited', format: (i) => n(280 + i * 62) },
      { id: 'intent', label: 'Intent score', format: (_, s) => `${Math.round(20 + s * 0.75)}` },
      { id: 'cohort', label: 'Interested cohort', format: (i) => n(350 + i * 70) },
    ],
  },
  {
    id: 'pyl',
    label: 'Press Your Luck',
    spineStage: 'Activate',
    caption: 'You fund spins with points. Watch/answer unlocks the wheel. Wins hit the feed → more spins + product listing.',
    dialLabel: 'Spin pool funding',
    scopeLabel: 'Earn path intensity',
    scopeMinLabel: 'Video only',
    scopeMaxLabel: 'Video + quiz',
    pinLabel: 'Wheel',
    dotSemantic: 'Spinners',
    status: 'Live',
    showFavoritePulse: true,
    showFeedBlip: true,
    act: 3,
    results: [
      { id: 'spins', label: 'Spins earned', format: (i) => n(120 + i * 40) },
      { id: 'favorites', label: 'Favorited', format: (i) => n(90 + i * 35) },
      { id: 'network', label: 'Feed → re-entries', format: (i) => n(30 + i * 18) },
      { id: 'pdp', label: 'Product views', format: (i) => n(200 + i * 55) },
    ],
  },
  {
    id: 'learn',
    label: 'Learn & Earn',
    spineStage: 'Capture',
    caption: 'Make the bounty worth the video and the quiz — or they abandon mid-way.',
    dialLabel: 'Bounty',
    pinLabel: 'Mission',
    dotSemantic: 'Completions',
    status: 'Live',
    act: 3,
    results: [
      { id: 'starts', label: 'Started', format: (i) => n(500 + i * 40) },
      { id: 'done', label: 'Completed', format: (i) => n(80 + i * 55) },
      { id: 'finish', label: 'Finish rate', format: (i) => `${Math.round(12 + i * 0.7)}%` },
      { id: 'cost', label: 'Est. cost / complete', format: (i) => `$${(2.4 - i * 0.012).toFixed(2)}` },
    ],
  },
  {
    id: 'geo',
    label: 'Geo / event',
    spineStage: 'Activate',
    caption: 'Aim a market. Pay for verified show-ups — $0 upfront if you want results-only.',
    dialLabel: 'Incentive intensity',
    scopeLabel: 'Radius',
    scopeMinLabel: 'Tight',
    scopeMaxLabel: 'Wide',
    pinLabel: 'Market',
    dotSemantic: 'Show-ups',
    status: 'Live',
    showPayPerResult: true,
    act: 5,
    results: [
      { id: 'scope', label: 'In radius', format: (i, s) => n(200 + i * 30 + s * 40) },
      { id: 'shows', label: 'Verified show-ups', format: (i, s) => n(20 + i * 12 + s * 4) },
      { id: 'cpa', label: 'Est. cost / show-up', format: (i) => `$${(18 - i * 0.08).toFixed(0)}` },
      { id: 'upfront', label: 'Upfront', format: () => '$0' },
    ],
  },
  {
    id: 'weather',
    label: 'Weather trigger',
    spineStage: 'Activate',
    caption: 'Rained on the round? Wind 25+? Regional backfill? Serve gear at felt need — not spray.',
    dialLabel: 'Trigger reach',
    scopeLabel: 'Condition mix',
    scopeMinLabel: 'Day-of only',
    scopeMaxLabel: '7-day + always-wet',
    pinLabel: 'Condition',
    dotSemantic: 'Matched golfers',
    status: 'Live',
    act: 5,
    results: [
      { id: 'matched', label: 'Matched golfers', format: (i, s) => n(150 + i * 45 + s * 60) },
      { id: 'served', label: 'Messages served', format: (i, s) => n(120 + i * 40 + s * 50) },
      { id: 'relevance', label: 'Relevance', format: (i) => `${Math.round(55 + i * 0.4)}%` },
      { id: 'waste', label: 'Spray waste', format: (i) => `${Math.round(40 - i * 0.28)}%` },
    ],
  },
  {
    id: 'course',
    label: 'Course off-peak',
    spineStage: 'Activate',
    caption: 'Fill dead tee times with a carrot. Lower still works — just thinner.',
    dialLabel: 'Points / round incentive',
    scopeLabel: 'Window',
    scopeMinLabel: 'Narrow',
    scopeMaxLabel: 'All off-peak',
    pinLabel: 'Course',
    dotSemantic: 'Rounds filled',
    status: 'Live',
    showPayPerResult: true,
    act: 5,
    results: [
      { id: 'slots', label: 'Slots filled', format: (i, s) => n(8 + i * 0.35 + s * 0.15) },
      { id: 'fill', label: 'Fill rate', format: (i) => `${Math.round(15 + i * 0.65)}%` },
      { id: 'per', label: 'Est. $ / round', format: (i) => `$${(12 - i * 0.04).toFixed(0)}` },
      { id: 'hands', label: 'Hands up', format: (i) => n(40 + i * 8) },
    ],
  },
  {
    id: 'cohort',
    label: 'Cohort',
    spineStage: 'Cohort',
    caption: 'Hands + favorites + bag signals → a segment you can actually work — not a dead CSV.',
    dialLabel: 'Signal depth',
    scopeLabel: 'Segment focus',
    scopeMinLabel: 'All hands',
    scopeMaxLabel: 'High intent only',
    pinLabel: 'Segment',
    dotSemantic: 'In cohort',
    status: 'Live',
    showFavoritePulse: true,
    act: 4,
    results: [
      { id: 'size', label: 'Cohort size', format: (i, s) => n(800 - s * 4 + i * 2) },
      { id: 'fav', label: 'With favorite', format: (i) => n(200 + i * 40) },
      { id: 'conf', label: 'Confidence', format: (i) => `${Math.round(40 + i * 0.5)}%` },
      { id: 'ready', label: 'Activation-ready', format: (i, s) => n(100 + i * 25 + s * 2) },
    ],
  },
  {
    id: 'offer',
    label: 'Follow-up offer',
    spineStage: 'Offer',
    caption: 'Capture isn’t the end. Unlisted path + offer strength for people who already raised a hand.',
    dialLabel: 'Offer strength',
    scopeLabel: 'Audience',
    scopeMinLabel: 'All entrants',
    scopeMaxLabel: 'High intent only',
    pinLabel: 'Offer',
    dotSemantic: 'Claims',
    status: 'Live',
    act: 6,
    results: [
      { id: 'eligible', label: 'Eligible', format: (i, s) => n(600 - s * 3) },
      { id: 'claims', label: 'Claims', format: (i, s) => n(40 + i * 18 + (100 - s) * 0.2) },
      { id: 'rate', label: 'Claim rate', format: (i) => `${Math.round(8 + i * 0.45)}%` },
      { id: 'unlisted', label: 'Unlisted path', format: () => 'On' },
    ],
  },
  {
    id: 'contained',
    label: 'Contained %',
    spineStage: 'Convert',
    caption: 'They earned points activating for you. Unlock a contained discount when those points hit your SKU — not a public coupon.',
    dialLabel: '% unlock with points',
    scopeLabel: 'Points/cash split',
    scopeMinLabel: '30% pts',
    scopeMaxLabel: '100% pts',
    pinLabel: 'Your SKU',
    dotSemantic: 'Redeems',
    status: 'Live',
    act: 7,
    results: [
      { id: 'wallet', label: 'With points', format: (i) => n(300 + i * 20) },
      { id: 'redeems', label: 'Redeems on you', format: (i, s) => n(25 + i * 14 + s * 0.3) },
      { id: 'unlock', label: 'Unlock', format: (i) => `${Math.round(5 + i * 0.2)}%` },
      { id: 'loop', label: 'Loop', format: () => 'Closed' },
    ],
  },
]

export const SPINE_STAGES = [
  'Aware',
  'Capture',
  'Cohort',
  'Activate',
  'Offer',
  'Convert',
  'Sustain',
] as const

export function getMode(id: string): LabMode {
  return LAB_MODES.find((m) => m.id === id) ?? LAB_MODES[0]
}
